"""Data model for an embedding."""
from dataclasses import dataclass
from typing import List
from datetime import datetime


@dataclass
class Embedding:
    """
    A vector representation of text content generated by the Cohere model, 
    associated with its source page and metadata.
    """
    id: str
    chunk_id: str
    vector: List[float]
    model_name: str
    created_at: datetime
    
    def __post_init__(self):
        """Validate the Embedding after initialization."""
        if not self.id:
            raise ValueError("Embedding.id cannot be empty")
        if not self.chunk_id:
            raise ValueError("Embedding.chunk_id cannot be empty")
        if not self.vector:
            raise ValueError("Embedding.vector cannot be empty")
        if len(self.vector) == 0:
            raise ValueError("Embedding.vector must contain at least one value")
        if not self.model_name:
            raise ValueError("Embedding.model_name cannot be empty")